POST https://4d5cy2i133.execute-api.us-west-2.amazonaws.com/prod/convertr_request
Accept: application/json
Content-Type': application/json

{
    "formid": 1806,
    "linkid": 10299,
    "pubid": 11007,
    "dataload": "form[salesrep_name]=test name"
}









# "form[salesrep_name]"
# "form[client_name]"
# "form[client_company]"
# "form[client_phone]"
# "form[client_email]"
# "form[ws_imp]"
# "form[ws_imp]"
# "form[ws_timetotalk]"
# "form[ws_version_cb][]"
# "form[ws_version_cb][]"
# "form[number_of_servers]"
# "form[vendors_server_gen]"
# "form[onprem_or_azure]"
# "form[onprem_or_azure]"
# "form[onprem_or_azure]"
# "form[onprem_or_azure]"
# "form[onprem_or_azure]"
# "form[onprem_or_azure]"
# "form[onprem_or_azure]"
# "form[onprem_plan]"
# "form[onprem_plan]"
# "form[onprem_plan]"
# "form[onprem_plan]"
# "form[onprem_plan]"
# "form[budget_allocated]"
# "form[budget_allocated]"
# "form[budget_allocated_amt]"
# "form[infra_req][]"
# "form[infra_req][]"
# "form[infra_req][]"
# "form[infra_req][]"
# "form[infra_req][]"
# "form[infra_req_compute]"
# "form[infra_req_storage]"
# "form[infra_req_networking]"
# "form[feedback_gen10_server]"
# "form[feedback_gen10_server]"
# "form[send_resource]"
# "form[send_resource]"
# "form[resource_to_send]"
# "form[next_steps]"
# "form[meet_with_specialist]"
# "form[meet_with_specialist]"
# "form[specialist_meeting_datetime]"
# "form[other_stakeholders]"
# "form[other_stakeholders]"
# "form[other_stakeholders_details]"
# "form[other_questions]"
# "form[other_questions]"
# "form[optin][terms]"
# "form[optin][contactTypes][]"
# "form[optin][contactTypes][]"
# "form[optin][contactTypes][]"
# "form[optin][contactTypes][]"
# "form[submit]"
# "form[_trans]"